[workspace]
members = ["martin", "martin-tile-utils", "martin-mbtiles"]

[workspace.package]
edition = "2021"
rust-version = "1.65"
repository = "https://github.com/maplibre/martin"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
actix = "0.13"
actix-cors = "0.6"
actix-http = "3"
actix-rt = "2"
actix-web = "4"
anyhow = "1.0"
async-trait = "0.1"
bbox = "0.11.2"
brotli = "3"
cargo-husky = { version = "1", features = ["user-hooks"], default-features = false }
clap = { version = "4", features = ["derive"] }
criterion = { version = "0.5", features = ["async_futures", "async_tokio", "html_reports"] }
ctor = "0.2"
deadpool-postgres = "0.10"
env_logger = "0.10"
flate2 = "1"
futures = "0.3"
indoc = "2"
itertools = "0.11"
log = "0.4"
martin-mbtiles = { path = "./martin-mbtiles", version = "0.2.0", default-features = false }  # disable CLI tools
martin-tile-utils = { path = "./martin-tile-utils", version = "0.1.0" }
nalgebra = { version = "0.22.1", features = ["serde-serialize"] }
num_cpus = "1"
openssl = "0.10"
pmtiles = { version = "0.2.2", features = ["mmap-async-tokio", "tilejson"] }
postgis = "0.9"
postgres = { version = "0.19", features = ["with-time-0_3", "with-uuid-1", "with-serde_json-1"] }
postgres-openssl = "0.5"
postgres-protocol = "0.6"
regex = "1"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
spreet = { version = "0.8", default-features = false }
sqlx = { version = "0.7.0-alpha.3", features = ["sqlite", "runtime-tokio-native-tls"] }
subst = { version = "0.2", features = ["yaml"] }
thiserror = "1"
tilejson = "0.3"
tokio = { version = "1.29.0", features = ["macros","rt-multi-thread"] }

[profile.dev.package.sqlx-macros]
# See https://github.com/launchbadge/sqlx#compile-time-verification
opt-level = 3
