[package]
name = "martin-mbtiles"
version = "0.2.2"
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>", "MapLibre contributors"]
description = "A simple low-level MbTiles access and processing library, with some tile format detection and other relevant heuristics."
keywords = ["mbtiles", "maps", "tiles", "mvt", "tilejson"]
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[features]
# TODO: Disable "cli" feature in default builds
default = ["cli"]
cli = ["dep:anyhow", "dep:bbox", "dep:clap", "dep:nalgebra","dep:tokio"]

[dependencies]
futures.workspace = true
log.workspace = true
martin-tile-utils.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tilejson.workspace = true

# Bin dependencies
anyhow = { workspace = true, optional = true }
bbox = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
nalgebra = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
# For testing, might as well use the same async framework as the Martin itself
actix-rt.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "mbtiles"
path = "src/bin/main.rs"
required-features = ["cli"]
